# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a9722c54ab2c60b1db42ebcde3ca91551d78620e5917884bc062b9c8d07fb00b48c56519f146d5f51b2bd2b363e6c88f9620173d16c5067aeea07af5c6962926

test:
  secret_key_base: 98159073c25003bcfaab64a54dc222d504feaf07a8424e08de60aabea7e2dae12e2ec3fc85d21b9659622db6dd1c09d68f21aabc64a113dccfd28d0419b0138b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
